### ISSUE TITLE
Update to Unicode 15

### ISSUE THREAD

**Issue by zacknewman** [sancane/precis#38]
Is there any plan to update to Unicode 15? Related to this, does it matter that [`precis-core`](https://github.com/sancane/precis/blob/main/precis-core/build.rs#L11) uses a different version than [`precis-profiles`](https://github.com/sancane/precis/blob/main/precis-profiles/build.rs#L9)? Seeing how `precis-profiles` relies on `precis-core`, doesn't that mean they should be based on the same version?

**Comment by sancane** [comment]
The Unicode version used for this release is the one stated by the latest approbed expert review in [IANA](https://www.iana.org/assignments/precis-tables-6.3.0/precis-tables-6.3.0.xhtml). Until a new "PRECIS Derived Property
   Value" table is updated, I'll stick to it in order to avoid unexected behaviours.

**Comment by sancane** [comment]
That makes sense. I've updated precis-profiles to utilize the latest Unicode 15.1.0.
Regards.
